language: node_js
os: linux
arch:
  - amd64
  - arm64

branches: main

stages:
node_js:
  - 16.9

services:
  - docker

install:
  - docker build -t "$DOCKER_IMAGE_NAME":"$TRAVIS_BRANCH" .

before_deploy:
  - docker run "$DOCKER_IMAGE_NAME" yarn run test

deploy:
  - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE_NAME":"$TRAVIS_BRANCH"