language: node_js
os: linux
arch:
  - amd64
  - arm64

#branches:
#  only:
#    - main

stages:
node_js:
  - 16.9

services:
  - docker

before_install:
  - docker build -t "$DOCKER_IMAGE_NAME":"$TRAVIS_BRANCH" .
  - docker run "$DOCKER_IMAGE_NAME" npm run test

install:
  - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE_NAME":"$TRAVIS_BRANCH"