language: node_js
os: linux
arch:
  - amd64
  - arm64

#branches:
#  only:
#    - main

stages:
node_js:
  - 16.9

services:
  - docker

before_install:
  - docker build -t "$DOCKER_IMAGE_NAME":latest .
  - docker tag "$DOCKER_IMAGE_NAME":latest "$DOCKER_IMAGE_NAME":git-"$TRAVIS_BRANCH"
  - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE_NAME":git-"$TRAVIS_BRANCH"
  - docker push "$DOCKER_IMAGE_NAME":"latest"